apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: a
  source:
    repoURL: https://github.com/Phamdinhhuyy/Test_ArgoCD.git
    targetRevision: HEAD
    path: ./
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image
          value: "nginx:latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
